heat_map/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('map.urls')),
]

map/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

# Url file to differentiate file from other url files 
app_name = 'base'

# Paths point to different url templates
urlpatterns = [
    path('', views.home, name='home'),
    path('map/', views.print_map, name='map'),
    path('upload/', views.multiple_upload, name='upload'),
    path('guide/', views.guide, name='guide'),
    path('about/', views.about, name='about'),
    path('login/', views.login, name='login')
]

# Paths to server media folder
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/models.py
from django.db import models
from django.core.validators import int_list_validator
from .scripts import metadata_extractor

# Holds a road image and number of cracks in image
class RoadImage(models.Model):
    image = models.ImageField()
    nDmg = models.IntegerField(default=-1)

    # Returns coordinates from image, in key value pair.
    # Latitude      = coordinates['latitude']
    # Longditude    = coordinates['longditude']
    def get_coordinates(self):
        return metadata_extractor.get_dd(self.image)

    # Returns image
    def get_image(self):
        return self.image

    # Setts new image
    def set_image(self, img):
        self.image = img

    # Returns number of cracks in image
    def get_n_dmg(self):
        return self.nDmg

    # Set number of cracks in image
    def set_n_dmg(self, nDmg):
        self.nDmg = nDmg
        
    def __str__(self):
        return self.image.name

map/views.py
from django.shortcuts import render
from django.conf import settings

from .models import RoadImage
##from . import tasks

# Prints map and passes a coordinates list equal to number 
# of cracks from images
def print_map(request):
    roadImages = RoadImage.objects.all()
    len_roadImages = len(roadImages)
    coordinates = []
    
    unclassified_img = 0 
    used_img = 0
    
    for roadImage in roadImages:
        n = roadImage.get_n_dmg()
        coord = roadImage.get_coordinates()
              
        if 0 < n:
            used_img += 1
            for i in range(n):
                coordinates.append([coord['latitude'], coord['longditude']])
        if -1 == n:
            unclassified_img += 1	

       	roadImage.save()

    if settings.DEBUG:
        print('Used images: ', used_img)
        print('Classified images: ', (len(roadImages) - unclassified_img))
        print('Total images: ', len(roadImages))
        
    return render(request, 'map/map.html', {'coordinates':coordinates, 
                                            'used_img':used_img, 
                                            'unclassified_img':unclassified_img, 
                                            'total_img':len_roadImages})

def login(request):
    return render(request, 'login/login.html',{})

def home(request):
    roadImages = RoadImage.objects.all()
    coordinates = []

    for roadImage in roadImages:
        n = roadImage.get_n_dmg()
        coord = roadImage.get_coordinates()

        if 0 < n:
            for i in range(n):
                coordinates.append([coord['longditude'], coord['latitude']])
                
    return render(request, 'home/home.html', {'coordinates':coordinates})

def about(request):
    return render(request, 'about/about.html')
def guide(request):
    return render(request, 'guide/guide.html',{})

# Uploads files and spawns a proccess to classify image
def multiple_upload(request):
    if 'POST' == request.method:
        for img in request.FILES.getlist('file'):
            if img.name.lower().endswith('.jpg'):
                roadImage = RoadImage()
                roadImage.image = img
                roadImage.save()
                
                tasks.set_n_dmg.delay(roadImage.id)
            
            elif settings.DEBUG:
                print('Wrong file type, file not uploaded')



    return render(request, 'imgUpload/imgUpload.html', {})

map/templates/about/about.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="/static/assets/css/Team-Boxed.css">
    <div class="team-boxed">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Team </h2>
                <p class="text-center">A bunch of dudes doing BSC</p>
            </div>
            <div class="row people">
                <div class="col-md-6 col-lg-4 item">
                    <div class="box">
                        <img class="rounded-circle" src="/static/images/thinking.png">
                        <h3 class="name">Eirik Gustafsson Gribbestad</h3>
                        <p class="title">Lead web developer</p>
                        <p class="description">3rd year automation engineering student. A jolly good fella and beef connoisseur</p>
                        <div class="social"><a href="#"><i class="fa fa-facebook-official"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 item">
                    <div class="box">
                            <img class="rounded-circle" src="/static/images/thinking.png">
                        <h3 class="name">Sivert Løken</h3>
                        <p class="title">Front-end and auto-encoder engineer</p>
                        <p class="description">3rd year automation engineering student. Fond of both memes and dark themes.</p>
                        <div class="social"><a href="#"><i class="fa fa-facebook-official"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 item">
                    <div class="box">
                            <img class="rounded-circle" src="/static/images/thinking.png">
                        <h3 class="name">Ole-martin Steinnes</h3>
                        <p class="title">Object-detection engineer</p>
                        <p class="description">3 year automation engineering student. Sworn to linux, slave to the console. </p>
                        <div class="social"><a href="#"><i class="fa fa-facebook-official"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
{% endblock %}

map/templates/guide/guide.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="/static/assets/css/guide.css">
<div class="guide">
    <header class="masthead">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-md-6 col-lg-4 item">
                    <div class="box">
                        <h1 class="font-weight-light">Getting started</h1>
                        <p class="lead">A quick guide to get you started using Road Classifier</p>
                    </div>
                </div>
            </div>
    </header>
    <body>
        <div class="row people">
            <div class="col-md-6 col-lg-4 item">
                <div class="box h-100">
                    <p class="title">First step</p>
                    <p class="description">
                        The first thing required is a folder containing images in .jpg format.
                        We have trained the model to identify distresses in the road surface from images
                        taken at 30 degrees angle from the dashboard and onto the road. Therefore it is
                        recommended to use similar approach when taking new images to get best results.
                        For the model to be able to plot a the density of damage in the map, all images must
                        be have a GPS-metadata section with GPS data in DMS format.
                    </p>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 item">
                <div class="box h-100">
                    <p class="title">Second step</p>
                    <p class="description">
                    When a folder with images has been uploaded, a script will
                    fetch each image, send it to a docker-api and return the labeled XML information.
                    The XML information will then be paresed and the number of cracks for each image will be retrieved.
                    Note that this process can take anywhere from 5 to 25 seconds per image, so large folders will 
                    take some time.
                    </p>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 item">
                    <div class="box h-100">
                        <p class="title">Finally</p>
                        <p class="description">
                        Once the model has predicted each image in the uploaded folder, it will 
                        plot the frequency and intensity of damage of the road surface as a heat-map. 
                        You can now go to the "map" section of the page and inspect the road network for large areas.
                        </p>
                    </div>
                </div>
            </div>
    </body>
    {% endblock %}

map/templates/home/home.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<html>

<head>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>

    <style>
        .leaflet-container {
            margin-left: auto;
            margin-right: auto;
            margin-top: auto;
            margin-bottom: auto;
            height: 50vh;
            width: 100%;
            /*
            padding: 20px 20px 20px 20px;
            */
        }
    </style>
</head>

<body>

    <div id="map"></div>

    <!-- <script src="../node_modules/simpleheat/simpleheat.js"></script>
        <script src="../src/HeatLayer.js"></script> -->

    <script src="{% static 'js/leaflet-heat.js' %}"></script>

    <!--<script src="http://leaflet.github.io/Leaflet.markercluster/example/realworld.10000.js"></script>-->
    <script>
        var map = L.map('map');
        map.setView([65.24751, 14.23828], 5);
        var tiles = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        // addressPoints = addressPoints.map(function (p) { return [p[0], p[1]]; });
        // console.log(addressPoints);
        // var heat = L.heatLayer(addressPoints).addTo(map);

        var newPoints = {{ coordinates }};

        if (1 < newPoints.length) {
            var heat = L.heatLayer(newPoints).addTo(map);
        } else {
            console.log('empty coordinates array');
        }


    </script>
    <div class="highlight-blue" style="background-color: rgb(255,255,255);">
        <div class="container"></div>
    </div>
    <div class="features-boxed">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Road Classifier</h2>
                <p class="text-center">Check the condition of your local road.</p>
            </div>
            <div class="row justify-content-center features">
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box h-100"><i class="fa fa-map-marker icon"></i>
                        <h3 class="name">Upload Images</h3>
                        <p class="description">Provide road images coupled with coordinates in the metadata to render a condition predicton   
                        </p><a href="{% url 'base:upload' %}" class="learn-more">Upload here »</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box h-100"><i class="fa fa-clock-o icon"></i>
                        <h3 class="name">Check the status of your upload</h3>
                        <p class="description">Processing images takes time. Click here to see the current status of your query.</p><a href="#" class="learn-more">Check status »</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box h-100"><i class="fa fa-list-alt icon"></i>
                        <h3 class="name">Getting started</h3>
                        <p class="description">Looking for a quick getting started guide? Head over to the information page</p><a href="#" class="learn-more">Learn more »</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="projects-clean"></div>
</body>
</html>
{% endblock %}

map/templates/imgUpload/imgUpload.html
{% extends 'index.html' %}

{% load static %}

{% block content %}

<html>
    <head>
        <title>Upload pictures</title>
        <link href="{% static 'css/imgUpload/imgUpload.css' %}" type="text/css" rel="stylesheet"/>
    </head>
    <body>
        <form class="dropzone" action="{% url 'base:upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="fallback">
                <input name="file" type="file" multiple />
            </div>
        </form>
        <script src="{% static 'js/dropzone.js' %}"></script>
    </body>
</html>

{% endblock %}

map/templates/login/login.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<html>
<head>
    <link rel="stylesheet" href="/static/assets/css/Login-Form-Clean.css">
</head>
<body>
    <div class="login-clean">
        <form method="post">
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><i class="fa fa-key icon"></i></div>
            <div class="form-group"><input class="form-control" type="username" name="Username" placeholder="Username"></div>
            <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password"></div>
            <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Log In</button></div><a href="#" class="forgot">Forgot your username or password?</a></form>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>
{% endblock %}

map/templates/map/map.html
{% extends 'index.html' %}

{% load static %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>

    <style>
      .leaflet-container {margin-left:auto; 
                            margin-right:auto; 
                            margin-top:auto;
                            margin-bottom: auto;
                            height: 100%; 
                            width: 100%; 
                            padding: 20px 20px 20px 20px;}
    </style>
</head>
<body>

<div id="map"></div>

<!-- <script src="../node_modules/simpleheat/simpleheat.js"></script>
<script src="../src/HeatLayer.js"></script> -->

<script src="{% static 'js/leaflet-heat.js' %}"></script>

<!--<script src="http://leaflet.github.io/Leaflet.markercluster/example/realworld.10000.js"></script>-->
<script>
var map = L.map('map');
map.setView([65.24751, 14.23828], 5);
var tiles = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
}).addTo(map);

// addressPoints = addressPoints.map(function (p) { return [p[0], p[1]]; });
// console.log(addressPoints);
// var heat = L.heatLayer(addressPoints).addTo(map);

var newPoints = {{ coordinates }};

if (1 < newPoints.length) {
  var heat = L.heatLayer(newPoints).addTo(map);
} else {
  console.log('empty coordinates array');
}


</script>
</body> 
</html>
{% endblock %}

templates/base.html
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <link rel="stylesheet" type="text/css" href="{% static 'css/base/base.css' %}">

    </head>

    <body>
        <div class='page-header'>
            <title>Road classifier</title>
            <h1>Road classifier</h1>

            <h4>
                <b onclick="location.href='{% url 'home:map' %}'"><i class='fa fa-map'> Map</i></b>
                <b onclick="location.href='{% url 'home:upload' %}'"><i class='fa fa-folder'> Upload</i></b> 
            </h4>

        </div>

        <div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/baseh.html
{% load static %}

<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <!--
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base/base.css' %}">
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>

<body>

        <!--
            <div class='page-header'>

            <title>Road classifier</title>
            <h1>Road classifier</h1>
            <h4>
                <b onclick="location.href='{% url 'home:map' %}'"><i class='fa fa-map'> Map</i></b>
                <b onclick="location.href='{% url 'home:upload' %}'"><i class='fa fa-folder'> Upload</i></b> 
            </h4>
            -->

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Road Classifier</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="#">Upload</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </nav>
        <div>
            <div class="container-fluid text-center">
                <div class="row content">
                    <div class="col-sm-2 sidenav">
                        <div class="col-sm-2 sidenav">
                            <p><a href="#">Link</a></p>
                            <p><a href="#">Link</a></p>
                            <p><a href="#">Link</a></p>
                        </div>
                        <div class="col-sm-8 text-left">
                            <!--
                            {% block content %}
                            {% endblock %}
                            -->
                        </div>
                    </div>
                    <div class="col-sm-2 sidenav">
                    </div>
</body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Classifier of </title>
    <link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/static/assets/css/Features-Boxed.css">
    <link rel="stylesheet" href="/static/assets/css/Footer-Basic.css">
    <link rel="stylesheet" href="/static/assets/css/Navigation-with-Button.css">
    <link rel="stylesheet" href="/static/assets/css/styles.css">
</head>

<body style="height: 800px;">
    <div>
        <nav class="navbar navbar-light navbar-expand-md navigation-clean-button">
            <div class="container"><a class="navbar-brand" href="{% url 'base:home' %}">Road Classifier</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"
                    id="navcol-1">
                    <ul class="nav navbar-nav mr-auto">
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'base:home' %}">Home</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'base:map' %}">Map</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'base:upload' %}">Upload</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'base:guide' %}">Getting Started</a></li>
                    </ul><span class="navbar-text actions"> <a href="{% url 'base:login' %}" class="login">Log In</a>
        </nav>
    </div>
    {% block content %} 
    {% endblock %}
    <div class="footer-basic">
        <footer>
            <div class="social"></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="{% url 'base:home' %}">Home</a></li>
                <li class="list-inline-item"><a href="{% url 'base:about' %}">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"></li>
            </ul>
            <p class="copyright">Company Name © 2019</p>
        </footer>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>